name = "navs"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liqhlVAPMcA3nbuv"
GITHUB_OWNER = "leelp000"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nave-35f.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://nave-35f.pages.dev"

